### ISSUE TITLE
Support multiple bars?

### ISSUE THREAD

**Issue by johnallen3d** [FelixKratz/SbarLua#2]
I've managed to get something working by changing [this line](https://github.com/FelixKratz/SbarLua/blob/78dbd67b96d75c7ab99e3f952480b2f369ebdb83/src/sketchybar.c#L69) (and #75), compiling and copying to `~/.local/share/sketchybar_lua` with a different name. This is obviously not an ideal solution but I'm not sure what is.

- pass a build-time argument that automates what I did manually

or

- allow (somehow) for passing a runtime argument with the bar name

**Comment by FelixKratz** [comment]
I have added a new function where you can specify the bar name:
```bash
sbar.set_bar_name("bottom_bar")
```
which you can add to the example `sketchybarrc` right after requiring the module.

**Comment by johnallen3d** [comment]
Works like a charm, thanks @FelixKratz!
