### ISSUE TITLE
Execute Command with SKHD

### ISSUE THREAD

**Issue by matthewshammond** [FelixKratz/SbarLua#22]
I apologize for putting this in issues, as I could not find the discussions section.

Is it possible to execute an sbar command from the command line?  What I want to do is key bind with skhd the toggle swap menus and spaces.

**Comment by FelixKratz** [comment]
You can simply use the regular shell api even when using lua for all the event handling. I.e. simply running `sketchybar --trigger swap_menus_and_spaces` will suffice.
