### ISSUE TITLE
For sbar.exec(<cmd>, <callback>), <callback> is not called when <cmd> prints nothing

### ISSUE THREAD

**Issue by WantToLearnJapanese** [FelixKratz/SbarLua#24]
Currently, the simple workaround is appending `&& echo 1` to the `\<cmd\>`

**Comment by curiosusJR** [comment]
Hi, I meet a problem with the <callback> function too. It can not recive argument from <cmd>, I think. I executed the example command
 ```
sbar.exec("sleep 5 && echo TEST", function(result)
  print(result)
end)
```
and return nothing.
I wonder what`s wrong with it.

**Comment by WantToLearnJapanese** [comment]
@curiosusJR Sorry for the late reply.
I can't access the macOS right now.
But I am sure appending `&& echo 1` works. Since I actually used that for my scripts.

**Comment by XavierChanth** [comment]
I am looking checking for the built-in display which yields empty string if it doesn't find, so I appended: `grep -q 'Built-in' && echo 'true' || echo 'false'` works like a charm.

**Comment by FelixKratz** [comment]
Should be fixed. Exit code is now additionally send to the callback function: https://github.com/FelixKratz/SbarLua/commit/5cfb488806006230712e87da74d8e767072c5c29
