### ISSUE TITLE
Cannot build under x86_64

### ISSUE THREAD

**Issue by QuarterHeaven** [FelixKratz/SbarLua#30]
I'm currently using Intel version macbook and while `make install` it reports:

```
clang -std=c99 -O3 -g -shared -fPIC src/sketchybar.c src/cJSON.c src/parsing.c bin/liblua.a -Ilua-5.4.7/src -Lbin -llua -framework CoreFoundation -o bin/sketchybar.so
ld: warning: ignoring file 'bin/liblua.a[33](linit.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[33](linit.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[32](lutf8lib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[31](ltablib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[30](lstrlib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[29](loslib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[28](loadlib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[27](lmathlib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[26](liolib.o)': found architecture 'arm64', required architecture 'x86_64'
```

**Comment by thgilciffart** [comment]
Try the previous version, im on an intel hack and the previous version worked perfectly for me and fixed all my issues!

**Comment by FelixKratz** [comment]
Could you try latest commit? I dont have an intel mac anymore.

**Comment by thgilciffart** [comment]
> Could you try latest commit? I dont have an intel mac anymore.

`user on users-iMac ~ ❯ (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)
Cloning into '/tmp/SbarLua'...
remote: Enumerating objects: 356, done.
remote: Counting objects: 100% (163/163), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 356 (delta 65), reused 146 (delta 58), pack-reused 193
Receiving objects: 100% (356/356), 851.31 KiB | 5.22 MiB/s, done.
Resolving deltas: 100% (130/130), done.
mkdir bin
cd lua-5.4.7 && make
Guessing Darwin
/Library/Developer/CommandLineTools/usr/bin/make all SYSCFLAGS="-DLUA_USE_MACOSX -DLUA_USE_READLINE" SYSLIBS="-lreadline"
ar rcu liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lcorolib.o ldblib.o liolib.o lmathlib.o loadlib.o loslib.o lstrlib.o ltablib.o lutf8lib.o linit.o 
ranlib liblua.a
mv lua-5.4.7/src/liblua.a bin
clang -std=c99 -O3 -g -shared -fPIC -arch x86_64 src/sketchybar.c src/cJSON.c src/parsing.c bin/liblua.a -Ilua-5.4.7/src -Lbin -llua -framework CoreFoundation -o bin/sketchybar.so
ld: warning: ignoring file 'bin/liblua.a[33](linit.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[32](lutf8lib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[31](ltablib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[30](lstrlib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[29](loslib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[28](loadlib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[27](lmathlib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[26](liolib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[25](ldblib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[24](lcorolib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[23](lbaselib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[22](lauxlib.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[21](lzio.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[20](lvm.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[19](lundump.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[18](ltm.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[17](ltable.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[16](lstring.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[15](lstate.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[14](lparser.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[13](lopcodes.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[12](lobject.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[11](lmem.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[10](llex.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[9](lgc.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[8](lfunc.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[7](ldump.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[6](ldo.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[5](ldebug.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[4](lctype.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[3](lcode.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'bin/liblua.a[2](lapi.o)': found architecture 'arm64', required architecture 'x86_64'
Undefined symbols for architecture x86_64:
  "_luaL_checkversion_", referenced from:
      _luaopen_sketchybar in sketchybar-75d25a.o
  "_luaL_execresult", referenced from:
      _os_execute_sig in sketchybar-75d25a.o
  "_luaL_optlstring", referenced from:
      _os_execute_sig in sketchybar-75d25a.o
  "_luaL_ref", referenced from:
      _subscribe in sketchybar-75d25a.o
      _exec in sketchybar-75d25a.o
      _delay in sketchybar-75d25a.o
  "_luaL_setfuncs", referenced from:
      _luaopen_sketchybar in sketchybar-75d25a.o
  "_lua_createtable", referenced from:
      _callback_function in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _json_array_to_lua_table in parsing-d5c2c2.o
      _json_object_to_lua_table in parsing-d5c2c2.o
  "_lua_getfield", referenced from:
      _get_name_from_state in sketchybar-75d25a.o
      _get_name_from_state in sketchybar-75d25a.o
  "_lua_getglobal", referenced from:
      _luaopen_sketchybar in sketchybar-75d25a.o
  "_lua_gettop", referenced from:
      _animate in sketchybar-75d25a.o
      _animate in sketchybar-75d25a.o
      _set in sketchybar-75d25a.o
      _defaults in sketchybar-75d25a.o
      _bar in sketchybar-75d25a.o
      _callback_function in sketchybar-75d25a.o
      _callback_function in sketchybar-75d25a.o
      ...
  "_lua_next", referenced from:
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _parse_kv_table in parsing-d5c2c2.o
      _parse_kv_table in parsing-d5c2c2.o
      _parse_table_values_to_stack in parsing-d5c2c2.o
  "_lua_pcallk", referenced from:
      _animate in sketchybar-75d25a.o
      _callback_function in sketchybar-75d25a.o
      _callback_function in sketchybar-75d25a.o
      _delay_callback in sketchybar-75d25a.o
  "_lua_pushboolean", referenced from:
      _os_execute_sig in sketchybar-75d25a.o
      _json_array_to_lua_table in parsing-d5c2c2.o
      _json_array_to_lua_table in parsing-d5c2c2.o
      _json_object_to_lua_table in parsing-d5c2c2.o
      _json_object_to_lua_table in parsing-d5c2c2.o
  "_lua_pushcclosure", referenced from:
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      ...
  "_lua_pushinteger", referenced from:
      _json_array_to_lua_table in parsing-d5c2c2.o
      _json_object_to_lua_table in parsing-d5c2c2.o
  "_lua_pushnil", referenced from:
      _add in sketchybar-75d25a.o
      _json_array_to_lua_table in parsing-d5c2c2.o
      _json_object_to_lua_table in parsing-d5c2c2.o
      _parse_kv_table in parsing-d5c2c2.o
      _parse_table_values_to_stack in parsing-d5c2c2.o
  "_lua_pushnumber", referenced from:
      _json_array_to_lua_table in parsing-d5c2c2.o
      _json_object_to_lua_table in parsing-d5c2c2.o
  "_lua_pushstring", referenced from:
      _callback_function in sketchybar-75d25a.o
      _callback_function in sketchybar-75d25a.o
      _callback_function in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      ...
  "_lua_pushvalue", referenced from:
      _subscribe in sketchybar-75d25a.o
      _exec in sketchybar-75d25a.o
      _delay in sketchybar-75d25a.o
      _parse_table_values_to_stack in parsing-d5c2c2.o
      _parse_table_values_to_stack in parsing-d5c2c2.o
  "_lua_rawgeti", referenced from:
      _callback_function in sketchybar-75d25a.o
      _callback_function in sketchybar-75d25a.o
      _delay_callback in sketchybar-75d25a.o
  "_lua_rawseti", referenced from:
      _json_array_to_lua_table in parsing-d5c2c2.o
  "_lua_rotate", referenced from:
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
  "_lua_setfield", referenced from:
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      _luaopen_sketchybar in sketchybar-75d25a.o
      ...
  "_lua_settable", referenced from:
      _callback_function in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _json_object_to_lua_table in parsing-d5c2c2.o
      ...
  "_lua_settop", referenced from:
      _get_name_from_state in sketchybar-75d25a.o
      _get_name_from_state in sketchybar-75d25a.o
      _subscribe in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _add in sketchybar-75d25a.o
      _parse_kv_table in parsing-d5c2c2.o
      _parse_table_values_to_stack in parsing-d5c2c2.o
      ...
  "_lua_toboolean", referenced from:
      _hotload in sketchybar-75d25a.o
      _parse_kv_table in parsing-d5c2c2.o
  "_lua_tointegerx", referenced from:
      _animate in sketchybar-75d25a.o
  "_lua_tolstring", referenced from:
      _animate in sketchybar-75d25a.o
      _animate in sketchybar-75d25a.o
      _get_name_from_state in sketchybar-75d25a.o
      _get_name_from_state in sketchybar-75d25a.o
      _callback_function in sketchybar-75d25a.o
      _subscribe in sketchybar-75d25a.o
      _query in sketchybar-75d25a.o
      ...
  "_lua_tonumberx", referenced from:
      _delay in sketchybar-75d25a.o
      _parse_kv_table in parsing-d5c2c2.o
  "_lua_type", referenced from:
      _animate in sketchybar-75d25a.o
      _animate in sketchybar-75d25a.o
      _animate in sketchybar-75d25a.o
      _get_name_from_state in sketchybar-75d25a.o
      _get_name_from_state in sketchybar-75d25a.o
      _set in sketchybar-75d25a.o
      _set in sketchybar-75d25a.o
      _set in sketchybar-75d25a.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/sketchybar.so] Error 1`
here's my error message o nlatest

**Comment by ShroomKing** [comment]
@FelixKratz I suggest adding *.o object files to the `.gitignore` and deleting them from the repository, you pushed precompiled arm64 object files by accident

Compiling on Intel works fine as long as you run `make clean` before you run `make`

**Comment by FelixKratz** [comment]
Thanks for the heads up! Removed them just now.
