### ISSUE TITLE
Does this support adding graphs?

### ISSUE THREAD

**Issue by shajra** [FelixKratz/SbarLua#6]
I can add graphs using the shell API, but the things I'm trying on the Lua side aren't working.

After a while of banging on this, it occurred to me that the Lua API may not support more advanced bar types.  Before digging more into the code, I thought I'd ask the question here.

I tried things like this:

```lua
sbar.add("graph", "cpu.user", {
    width=75, ...
})
```

```lua
sbar.add("graph", "cpu.user", 75, {...})
```

```lua
sbar.add("graph", "cpu.user", "75", {...})
```

What made it clear that none of this was working was querying the bar to see what items were registered.  I could only get graphs registered when calling the `sketchybar` executable.

Curious if I missed something or if the functionality is not there yet.

**Comment by FelixKratz** [comment]
Graphs are not supported in this api currently, however it is really easy to add them in this function:
https://github.com/FelixKratz/SbarLua/blob/260de153682ad01e918a894fa9b4ac9eadb41004/src/sketchybar.c#L375

**Comment by FelixKratz** [comment]
Graphs are now supported.
